/**
 * Pre-generated WASM callback stubs for Emscripten addFunction replacement
 * 
 * These byte arrays create minimal WASM modules that wrap JS functions,
 * allowing them to be added to the WASM function table without runtime
 * WebAssembly compilation (which is blocked in Cloudflare Workers).
 * 
 * Generated by: scripts/generate-callback-stubs.js
 */

export const CALLBACK_STUB_BYTES: Record<string, Uint8Array> = {
  'v': new Uint8Array([0, 97, 115, 109, 1, 0, 0, 0, 1, 4, 1, 96, 0, 0, 2, 7, 1, 1, 101, 1, 102, 0, 0, 7, 5, 1, 1, 102, 0, 0]),
  'vi': new Uint8Array([0, 97, 115, 109, 1, 0, 0, 0, 1, 5, 1, 96, 1, 127, 0, 2, 7, 1, 1, 101, 1, 102, 0, 0, 7, 5, 1, 1, 102, 0, 0]),
  'vii': new Uint8Array([0, 97, 115, 109, 1, 0, 0, 0, 1, 6, 1, 96, 2, 127, 127, 0, 2, 7, 1, 1, 101, 1, 102, 0, 0, 7, 5, 1, 1, 102, 0, 0]),
  'viii': new Uint8Array([0, 97, 115, 109, 1, 0, 0, 0, 1, 7, 1, 96, 3, 127, 127, 127, 0, 2, 7, 1, 1, 101, 1, 102, 0, 0, 7, 5, 1, 1, 102, 0, 0]),
  'viiii': new Uint8Array([0, 97, 115, 109, 1, 0, 0, 0, 1, 8, 1, 96, 4, 127, 127, 127, 127, 0, 2, 7, 1, 1, 101, 1, 102, 0, 0, 7, 5, 1, 1, 102, 0, 0]),
  'i': new Uint8Array([0, 97, 115, 109, 1, 0, 0, 0, 1, 5, 1, 96, 0, 1, 127, 2, 7, 1, 1, 101, 1, 102, 0, 0, 7, 5, 1, 1, 102, 0, 0]),
  'ii': new Uint8Array([0, 97, 115, 109, 1, 0, 0, 0, 1, 6, 1, 96, 1, 127, 1, 127, 2, 7, 1, 1, 101, 1, 102, 0, 0, 7, 5, 1, 1, 102, 0, 0]),
  'iii': new Uint8Array([0, 97, 115, 109, 1, 0, 0, 0, 1, 7, 1, 96, 2, 127, 127, 1, 127, 2, 7, 1, 1, 101, 1, 102, 0, 0, 7, 5, 1, 1, 102, 0, 0]),
  'iiii': new Uint8Array([0, 97, 115, 109, 1, 0, 0, 0, 1, 8, 1, 96, 3, 127, 127, 127, 1, 127, 2, 7, 1, 1, 101, 1, 102, 0, 0, 7, 5, 1, 1, 102, 0, 0]),
  'iiiii': new Uint8Array([0, 97, 115, 109, 1, 0, 0, 0, 1, 9, 1, 96, 4, 127, 127, 127, 127, 1, 127, 2, 7, 1, 1, 101, 1, 102, 0, 0, 7, 5, 1, 1, 102, 0, 0]),
  'di': new Uint8Array([0, 97, 115, 109, 1, 0, 0, 0, 1, 6, 1, 96, 1, 127, 1, 124, 2, 7, 1, 1, 101, 1, 102, 0, 0, 7, 5, 1, 1, 102, 0, 0]),
  'dii': new Uint8Array([0, 97, 115, 109, 1, 0, 0, 0, 1, 7, 1, 96, 2, 127, 127, 1, 124, 2, 7, 1, 1, 101, 1, 102, 0, 0, 7, 5, 1, 1, 102, 0, 0]),
  'id': new Uint8Array([0, 97, 115, 109, 1, 0, 0, 0, 1, 6, 1, 96, 1, 124, 1, 127, 2, 7, 1, 1, 101, 1, 102, 0, 0, 7, 5, 1, 1, 102, 0, 0]),
  'iid': new Uint8Array([0, 97, 115, 109, 1, 0, 0, 0, 1, 7, 1, 96, 2, 127, 124, 1, 127, 2, 7, 1, 1, 101, 1, 102, 0, 0, 7, 5, 1, 1, 102, 0, 0]),
  'fi': new Uint8Array([0, 97, 115, 109, 1, 0, 0, 0, 1, 6, 1, 96, 1, 127, 1, 125, 2, 7, 1, 1, 101, 1, 102, 0, 0, 7, 5, 1, 1, 102, 0, 0]),
  'if': new Uint8Array([0, 97, 115, 109, 1, 0, 0, 0, 1, 6, 1, 96, 1, 125, 1, 127, 2, 7, 1, 1, 101, 1, 102, 0, 0, 7, 5, 1, 1, 102, 0, 0]),
};

// Pre-compiled modules (created at module load time)
let _compiledModules: Record<string, WebAssembly.Module> | null = null;

function getCompiledModules(): Record<string, WebAssembly.Module> {
  if (!_compiledModules) {
    _compiledModules = {};
    for (const [sig, bytes] of Object.entries(CALLBACK_STUB_BYTES)) {
      _compiledModules[sig] = new WebAssembly.Module(bytes);
    }
  }
  return _compiledModules;
}

/**
 * Convert a JavaScript function to a WASM-compatible function
 * using pre-compiled stub modules instead of runtime compilation.
 * 
 * This is a drop-in replacement for Emscripten's convertJsFunctionToWasm.
 */
export function convertJsFunctionToWasm(
  func: Function,
  sig: string
): Function {
  // Try WebAssembly.Function first (if supported)
  if (typeof WebAssembly.Function === 'function') {
    const sigToWasmTypes = (s: string) => {
      const typeNames: Record<string, string> = {
        'i': 'i32', 'j': 'i64', 'f': 'f32',
        'd': 'f64', 'e': 'externref', 'p': 'i32'
      };
      return {
        parameters: Array.from(s.slice(1), c => typeNames[c]),
        results: s[0] === 'v' ? [] : [typeNames[s[0]]]
      };
    };
    return new (WebAssembly as any).Function(sigToWasmTypes(sig), func);
  }

  // Fall back to pre-compiled stubs
  const modules = getCompiledModules();
  const module = modules[sig];
  if (!module) {
    throw new Error(`No pre-compiled stub for signature: ${sig}`);
  }

  const instance = new WebAssembly.Instance(module, { e: { f: func } });
  return instance.exports.f as Function;
}
