/**
 * Pre-compiled WASM callback stubs for Cloudflare Workers
 *
 * This module provides a drop-in replacement for Emscripten's `addFunction`
 * that works in Cloudflare Workers by using pre-compiled WASM modules
 * imported as static assets.
 *
 * USAGE:
 * ```typescript
 * import { convertJsFunctionToWasm, STUB_MODULES } from './workers-stubs';
 *
 * // Instead of: mod.addFunction(callback, 'iii')
 * const wasmFunc = convertJsFunctionToWasm(callback, 'iii');
 * ```
 *
 * Generated by: scripts/generate-callback-stubs.js
 */

// Import WASM modules as static assets
// Cloudflare Workers compiles these at deploy time
import stub_v from './wasm/v.wasm';
import stub_vi from './wasm/vi.wasm';
import stub_vii from './wasm/vii.wasm';
import stub_viii from './wasm/viii.wasm';
import stub_viiii from './wasm/viiii.wasm';
import stub_i from './wasm/i.wasm';
import stub_ii from './wasm/ii.wasm';
import stub_iii from './wasm/iii.wasm';
import stub_iiii from './wasm/iiii.wasm';
import stub_iiiii from './wasm/iiiii.wasm';
import stub_di from './wasm/di.wasm';
import stub_dii from './wasm/dii.wasm';
import stub_id from './wasm/id.wasm';
import stub_iid from './wasm/iid.wasm';
import stub_fi from './wasm/fi.wasm';
import stub_if from './wasm/if.wasm';

/**
 * Map of signature strings to pre-compiled WebAssembly modules.
 *
 * Signature format:
 * - First character = return type
 * - Subsequent characters = parameter types
 *
 * Type codes:
 * - 'v' = void
 * - 'i' = i32
 * - 'p' = i32 (pointer)
 * - 'j' = i64
 * - 'f' = f32
 * - 'd' = f64
 */
export const STUB_MODULES: Record<string, WebAssembly.Module> = {
  'v': stub_v,
  'vi': stub_vi,
  'vii': stub_vii,
  'viii': stub_viii,
  'viiii': stub_viiii,
  'i': stub_i,
  'ii': stub_ii,
  'iii': stub_iii,
  'iiii': stub_iiii,
  'iiiii': stub_iiiii,
  'di': stub_di,
  'dii': stub_dii,
  'id': stub_id,
  'iid': stub_iid,
  'fi': stub_fi,
  'if': stub_if,
};

/**
 * List of supported signatures.
 */
export const SUPPORTED_SIGNATURES = Object.keys(STUB_MODULES);

/**
 * Convert a JavaScript function to a WASM-compatible function.
 *
 * This is a drop-in replacement for Emscripten's `convertJsFunctionToWasm`
 * that works in Cloudflare Workers by using pre-compiled WASM stubs.
 *
 * @param func - The JavaScript function to wrap
 * @param sig - The Emscripten signature string (e.g., 'iii' for (i32, i32) -> i32)
 * @returns A WASM function that wraps the JavaScript function
 * @throws Error if the signature is not supported
 *
 * @example
 * ```typescript
 * const readCallback = (ptr: number, maxLen: number) => {
 *   // Read data...
 *   return bytesRead;
 * };
 * const wasmReadCallback = convertJsFunctionToWasm(readCallback, 'iii');
 * ```
 */
export function convertJsFunctionToWasm(
  func: Function,
  sig: string
): Function {
  const module = STUB_MODULES[sig];
  if (!module) {
    throw new Error(
      `No pre-compiled stub for signature: ${sig}. ` +
      `Supported signatures: ${SUPPORTED_SIGNATURES.join(', ')}`
    );
  }

  const instance = new WebAssembly.Instance(module, { e: { f: func } });
  return instance.exports.f as Function;
}

/**
 * Check if a signature is supported.
 *
 * @param sig - The Emscripten signature string
 * @returns true if the signature has a pre-compiled stub
 */
export function isSignatureSupported(sig: string): boolean {
  return sig in STUB_MODULES;
}

/**
 * Add a new signature at runtime (for testing/development only).
 *
 * NOTE: This will NOT work in Cloudflare Workers because it attempts
 * to create a WebAssembly.Module at runtime. Only use this in Node.js
 * or browser environments for testing.
 *
 * @param sig - The Emscripten signature string
 * @param bytes - The WASM module bytes
 */
export function registerSignature(sig: string, bytes: Uint8Array): void {
  if (typeof globalThis.process !== 'undefined' || typeof window !== 'undefined') {
    // Node.js or browser - runtime compilation allowed
    (STUB_MODULES as any)[sig] = new WebAssembly.Module(bytes);
  } else {
    throw new Error(
      'Cannot register signatures at runtime in Cloudflare Workers. ' +
      'Pre-generate the WASM stub using scripts/generate-callback-stubs.js'
    );
  }
}
